// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjsdxxpmpgkfqirxfjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqc2R4eHBtcGdrZnFpcnhmamxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTYzNTYsImV4cCI6MjA3MTE3MjM1Nn0.LfR1klyfKbLDdHfFdEEEllEdkUCFjpeK_yBczhVH0Dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});